CREATE TABLE [dbo].[Spart_BryanFinalImporta] (
  [UserId] [nvarchar](50) NOT NULL,
  [Date] [date] NOT NULL,
  [IsComplete] [bit] NULL,
  [LastUpdateDTm] [date] NOT NULL,
  [DOB] [nvarchar](50) NULL,
  [FirstName] [nvarchar](50) NULL,
  [Gender] [nvarchar](50) NULL,
  [Ident] [nvarchar](50) NULL,
  [LastName] [nvarchar](50) NULL,
  [Locale] [nvarchar](50) NULL,
  [EmploymentStatus] [nvarchar](50) NULL,
  [ProgramStatus] [nvarchar](50) NULL,
  [A1C_Question] [float] NULL,
  [AGE_Question] [nvarchar](50) NULL,
  [BMI_Question] [float] NULL,
  [BPMeds_Question] [varchar](50) NULL,
  [BPStratPointCalc_Question] [varchar](50) NULL,
  [DBP_Question] [varchar](50) NULL,
  [DIABETES_Question] [bit] NULL,
  [Eat1USA_Question] [float] NULL,
  [Eat2USA_Question] [float] NULL,
  [EnduranceDuration_Question] [varchar](50) NULL,
  [EnduranceFrequency_Question] [varchar](50) NULL,
  [Flexibility_Question] [varchar](50) NULL,
  [GLU_Question] [varchar](50) NULL,
  [HDL_Question] [varchar](50) NULL,
  [LDL_Question] [varchar](50) NULL,
  [overwhelmed_Question] [varchar](50) NULL,
  [QuitTobacco_Question] [varchar](50) NULL,
  [Resistance_Question] [varchar](50) NULL,
  [SBP_Question] [varchar](50) NULL,
  [TC_Question] [varchar](50) NULL,
  [Tobacco_Question] [varchar](50) NULL,
  [TobaccoProducts_Question] [varchar](50) NULL,
  [TRIG_Question] [varchar](50) NULL,
  [WAIST_Question] [varchar](50) NULL,
  [Weight_Question] [varchar](50) NULL,
  [EHGHighRiskCounter_Risk] [varchar](50) NULL,
  [EHGRiskIndicator_Risk] [varchar](50) NULL,
  [PrehyperBP] [varchar](50) NULL,
  [Gender1] [nvarchar](50) NULL,
  [Age] [nvarchar](50) NULL,
  [RiskLevel] [nvarchar](50) NULL,
  [DiagnosedDM] [nvarchar](50) NULL,
  [UndiagnosedDM] [varchar](50) NULL,
  [ControlledDM] [varchar](50) NULL,
  [Diabetes1] [float] NULL,
  [A1C1] [nvarchar](50) NULL,
  [Glucose1] [nvarchar](50) NULL,
  [BloodPressure] [nvarchar](50) NULL,
  [CountNormalBP] [varchar](50) NULL,
  [CountPrehyper] [varchar](50) NULL,
  [CountHyper] [varchar](50) NULL,
  [BPMeds] [varchar](50) NULL,
  [BPMedStatus] [nvarchar](50) NULL,
  [TotalCholesterol] [nvarchar](50) NULL,
  [HDL] [nvarchar](50) NULL,
  [LDL] [nvarchar](50) NULL,
  [Triglyceride] [nvarchar](50) NULL,
  [BMI] [nvarchar](50) NULL,
  [WaistCircum] [nvarchar](50) NULL,
  [CountofWCMale40] [varchar](50) NULL,
  [CountofWCMale40a] [varchar](50) NULL,
  [CountofWCFemale35] [varchar](50) NULL,
  [CountofWCFemale35a] [varchar](50) NULL,
  [TobaccoUse] [varchar](50) NULL,
  [TobaccoProducts] [nvarchar](50) NULL,
  [IntenttoQuit] [nvarchar](50) NULL,
  [Overwhelmed] [varchar](50) NULL,
  [BPReferral] [nvarchar](50) NULL,
  [DMReferral] [nvarchar](50) NULL,
  [TGReferral] [varchar](50) NULL
)
ON [PRIMARY]
GO