CREATE TABLE [dbo].[EHGAggregateTable] (
  [UserId] [nvarchar](50) NOT NULL,
  [Date] [datetime2] NOT NULL,
  [IsComplete] [bit] NOT NULL,
  [LastUpdateDTm] [datetime2] NOT NULL,
  [DOB] [nvarchar](1) NULL,
  [FirstName] [nvarchar](1) NULL,
  [Gender] [nvarchar](50) NOT NULL,
  [Ident] [nvarchar](1) NULL,
  [LastName] [nvarchar](1) NULL,
  [Locale] [nvarchar](50) NOT NULL,
  [EmploymentStatus] [nvarchar](50) NULL,
  [ProgramStatus] [nvarchar](50) NULL,
  [A1C_Question] [float] NULL,
  [AGE_Question] [tinyint] NOT NULL,
  [BMI_Question] [float] NULL,
  [BPMeds_Question] [tinyint] NULL,
  [BPStratPointCalc_Question] [tinyint] NOT NULL,
  [DBP_Question] [tinyint] NULL,
  [DIABETES_Question] [bit] NOT NULL,
  [Eat1USA_Question] [float] NOT NULL,
  [Eat2USA_Question] [float] NOT NULL,
  [EnduranceDuration_Question] [tinyint] NULL,
  [EnduranceFrequency_Question] [tinyint] NOT NULL,
  [Flexibility_Question] [tinyint] NOT NULL,
  [GLU_Question] [smallint] NULL,
  [HDL_Question] [tinyint] NULL,
  [LDL_Question] [smallint] NULL,
  [overwhelmed_Question] [bit] NOT NULL,
  [QuitTobacco_Question] [tinyint] NULL,
  [Resistance_Question] [tinyint] NOT NULL,
  [SBP_Question] [tinyint] NULL,
  [TC_Question] [smallint] NULL,
  [Tobacco_Question] [bit] NOT NULL,
  [TobaccoProducts_Question] [float] NULL,
  [TRIG_Question] [smallint] NULL,
  [WAIST_Question] [tinyint] NULL,
  [Weight_Question] [float] NULL,
  [EHGHighRiskCounter_Risk] [float] NULL,
  [EHGRiskIndicator_Risk] [tinyint] NULL,
  CONSTRAINT [PK_EHGAggregateTable] PRIMARY KEY CLUSTERED ([UserId])
)
ON [PRIMARY]
GO