CREATE TABLE [dbo].[LawrWSE] (
  [UserId] [nvarchar](50) NOT NULL,
  [Gender] [nvarchar](50) NOT NULL,
  [Locale] [nvarchar](50) NOT NULL,
  [TotalPoints] [tinyint] NOT NULL,
  [Welcome] [tinyint] NULL,
  [HRA_Screening_amp_Coaching] [tinyint] NULL,
  [Health_Assessment] [tinyint] NULL,
  [Health_Assessment2] [tinyint] NULL,
  [Health_Screening] [tinyint] NULL,
  [Biometrics_Complete] [tinyint] NULL,
  [Book_Appointment] [tinyint] NULL,
  [Health_Data_Form] [tinyint] NULL,
  [Results_Coaching_Complete] [tinyint] NULL,
  [Results_Coaching_Completed] [tinyint] NULL,
  [Coaching] [tinyint] NULL,
  [Follow_Up_Coaching] [tinyint] NULL,
  [FUCoaching_Completed] [tinyint] NULL,
  [Annual_Physical] [tinyint] NULL,
  [Annual_Physical_Submission] [tinyint] NULL,
  [Record_Your_Annual_Physical] [tinyint] NULL,
  [Healthy_Credits] [tinyint] NULL,
  [Wellness_Activity_Submission] [tinyint] NULL,
  [_5K_Community_Race] [tinyint] NULL,
  [Healthy_Break] [tinyint] NULL,
  [Flu_Shot] [tinyint] NULL,
  [Vision_Exam] [tinyint] NULL,
  [Dental_Exam] [tinyint] NULL,
  [Offline_Challenge] [tinyint] NULL,
  [Other] [tinyint] NULL,
  [Online_Programs_amp_Challenges] [tinyint] NULL,
  [Wellbeing123] [tinyint] NULL,
  [_1_point_s_for_reaching_milestone_One_Month_Madness_30000] [tinyint] NULL,
  [Adjustments_Redemptions] [tinyint] NULL,
  CONSTRAINT [PK_LawrWSE] PRIMARY KEY CLUSTERED ([UserId])
)
ON [PRIMARY]
GO